spring.application.name=Ticketgo

# C?u hình k?t n?i PostgreSQL Supabase
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.rdfnidhtqoyshjawnxqt&password=ticketgo@2026
spring.datasource.username=postgres.rdfnidhtqoyshjawnxqt
spring.datasource.password=ticketgo@2026
spring.datasource.driver-class-name=org.postgresql.Driver
supabase.url=https://rdfnidhtqoyshjawnxqt.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkZm5pZGh0cW95c2hqYXdueHF0Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MzQyNTA1NywiZXhwIjoyMDk5MDAxMDU3fQ.WWD9egyXInPgOOGLOkK_ZOWh0m-cFExmSiC1pNzROiU
supabase.bucket=movies
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Logging SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Upload file config
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# HikariCP settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.keepalive-time=300000

